framework:
    assets:
        version_format: '%%s?v=%%s'
        packages:
            bootstrap:
                base_path: '/bootstrap'
                version: '4.1.3'
            app:
                base_path: '/app'
                version: '1.0.0'
